### ISSUE TITLE
Card shows day of the week instead of hour in forecast pane

### ISSUE THREAD

**Issue by nepozs** [mawinkler/astroweather-card#1]
Card shows day of the week instead of hour in forecast pane
![astroweather_card_hours_issue_2022-02-16_00-38](https://user-images.githubusercontent.com/56661567/154169204-38f85553-0c2a-468e-ad09-5a59b9c86f8b.png)
 card installed using HACS (as custom Lovelace repository)
Changing UI language does not help (my locale is PL).

**Comment by kaizersoje** [comment]
Same here.

**Comment by mawinkler** [comment]
Thank you both for reporting. Fixed in [v0.1.1](https://github.com/mawinkler/astroweather-card/releases/tag/v0.1.1).
