### ISSUE TITLE
Unable to install via HACS

### ISSUE THREAD

**Issue by MajorAutomation** [mawinkler/astroweather-card#10]
Howdy,
I am trying to install via HACS, it fails on Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble.
I added successfully in HACS, but when installing as an Integration I get the above error.
In your documentation is says it has a dependency of [pyastroweatherio](https://github.com/mawinkler/pyastroweatherio) but has no info on how to install this?
Noob help please?
Thanks
Major

**Comment by mawinkler** [comment]
Are we talking about the integration or the lovelace card?
After installation of the integration a full restart of hass is required, as with all other integrations. The card requires the integration to work, so install it afterwards, after the integration is functional. Be sure to refresh your browser cache after the card installation.
Thy pyastroweatherio component is installed automatically during the installation of the integration. No worries here.
