### ISSUE TITLE
Temerature in miles?

### ISSUE THREAD

**Issue by heylers** [mawinkler/astroweather-card#11]
Nice.  Am noticing though that the the units for temperature on the chart are "MI" when in Fahrenheit ;)
![Untitled](https://github.com/mawinkler/astroweather-card/assets/50296870/6bf1fa4e-db01-4398-9a91-a9903dc71188)

**Comment by mawinkler** [comment]
Should be resolved with [v0.31](https://github.com/mawinkler/astroweather-card/releases/tag/v0.31.0) card and [v0.31](https://github.com/mawinkler/astroweather/releases/tag/v0.31.0) integration.
