### ISSUE TITLE
Pressure unit

### ISSUE THREAD

**Issue by zhenyatk** [mawinkler/astroweather-card#14]
![image](https://github.com/mawinkler/astroweather-card/assets/19464998/fd747045-c7f6-4b68-ae5d-6d613761957a)
Hello!
Wrong display pressure unit, in forecast set "mmHg" but at card display "hPa". Pressure value show right

**Comment by mawinkler** [comment]
Your issue is not about the AstroWeather Card, since AstroWeather does not have a pressure sensor
