### ISSUE TITLE
tap_action does not work

### ISSUE THREAD

**Issue by f-zappa** [mawinkler/astroweather-card#19]
Since there is a "tap_action" statement in the example configuration, I tried to use a url tap_action like this.

```
tap_action:
  action: url
  url_path: /lovelace-technik/astronomie
```
When I click the card, nothing happens. Any ideas what I'm doing wrong?

**Comment by mawinkler** [comment]
You're not doing anything wrong, I just disabled the tap_action for the card because I didn't find a useful tap action. What do you want to do?

**Comment by f-zappa** [comment]
I want to have a "mini" version of the card with very basic information (deepsky details and the condition graph), and clicking on it should navigate me to an "astro" subpage with the full astroweather plus some more things (at the moment mainly uptonight).

**Comment by mawinkler** [comment]
I just pushed an updated card to main (no release yet). Please report if this works for you.

**Comment by f-zappa** [comment]
Unfortunately, it doesn't work. Just to make sure I didn't mess it up, these were the steps I followed:
a) deleted astroweather-card.js and .gz from /www/community/astroweather-card
b) wget the recent version from the repo (astroweather-card.js)
c) gzip -k astroweather-card.js
d) reloaded the page in the browser and try
e) restartet homeassistant, reloaded once more and try
When I click on the card, still nothing happens. Tried different positions.

**Comment by mawinkler** [comment]
Also see the examples in the README

**Comment by f-zappa** [comment]
fascinating .. since I had not activated experimental features in HACS yet, I didn't know this.
I followed this procedure now. Still nothing happens when I click. Only difference: the update sensor gets active and wants me to "update" to the release version 0.50.4

**Comment by mawinkler** [comment]
Did you clean your browser cache?

**Comment by f-zappa** [comment]
Sure I did!

**Comment by mawinkler** [comment]
You could try to delete the .gz files in the cards directory and then reload with a clean cache?
If you review the `astroweather-card.js` there are two new/updated functions in line 1333ff:

```js
  _handlePopup(e, entity) {
    e.stopPropagation();
    this._handleClick(this, this._hass, this._config, this._config.tap_action, entity.entity_id || entity);
  }

  _handleClick(node, hass, config, actionConfig, entityId) {
    let e;

    switch (actionConfig.action) {
      case 'more-info': {
        e = new Event('hass-more-info', { composed: true });
        e.detail = { entityId };
        node.dispatchEvent(e);
        break;
      }
      case 'navigate': {
        if (!actionConfig.navigation_path) return;
        window.history.pushState(null, '', actionConfig.navigation_path);
        e = new Event('location-changed', { composed: true });
        e.detail = { replace: false };
        window.dispatchEvent(e);
        break;
      }
      case 'call-service': {
        if (!actionConfig.service) return;
        const [domain, service] = actionConfig.service.split('.', 2);
        const data = { ...actionConfig.data };
        hass.callService(domain, service, data);
        break;
      }
      case 'url': {
        if (!actionConfig.url_path) return;
        window.location.href = actionConfig.url_path;
        break;
      }
      case 'fire-dom-event': {
        e = new Event('ll-custom', { composed: true, bubbles: true });
        e.detail = actionConfig;
        node.dispatchEvent(e);
        break;
      }
    }
  }
```

**Comment by f-zappa** [comment]
Ok - now I forced my browser to forget about the complete cache once more and it works. Sorry for that, you don't need to investigate any further!

**Comment by mawinkler** [comment]
🌈 & 🎠
