### ISSUE TITLE
Help with Home Assistant Core 2022.5.5

### ISSUE THREAD

**Issue by maphilli14** [mawinkler/astroweather-card#5]
I have a working instance of your custom card on a different installation running Home Assistant 2021.11.5.  The actions for adding resources to lovelace seems different between the two.  The working one shows as:

![image](https://user-images.githubusercontent.com/6034105/176255503-593a13f4-93f0-4ee7-9bdb-480a9d7209ed.png)
![image](https://user-images.githubusercontent.com/6034105/176255589-520e0fa6-0586-47bc-b4df-6e12f0a2893d.png)

The newer, non working one I have to hack the URL to get into resources as:

hacsIP.local:8123/config/lovelace/resources

![image](https://user-images.githubusercontent.com/6034105/176255755-15cce072-4153-40c1-b795-5b533b1c3629.png)

the files are there, on docker as:
```

pi@astrocart:~ $ sudo docker exec -it homeassistant ls -la /config/www/custom-lovelace/astroweather-card/
total 44
drwxr-xr-x    2 1000     1000          4096 Jun 27 16:23 .
drwxr-xr-x    3 1000     1000          4096 Jun 27 16:23 ..
-rwxr-xr-x    1 1000     1000          6715 Jun 27 16:23 astroweather-card-editor.js
-rwxr-xr-x    1 1000     1000         24854 Jun 27 16:23 astroweather-card.js
pi@astrocart:~ $


```

However, the entity does not show up:

![image](https://user-images.githubusercontent.com/6034105/176255984-543fc193-3692-418f-8f26-45aebc715473.png)

**Comment by mawinkler** [comment]
Hi @maphilli14, I have the feeling that this is a documentation issue. I assume that you did the manual installation? If so, again assuming that you have HACS, can you try to add the card via the custom repositories in HACS and report back? That's the way I'm doing it in my environment currently running on 2022.6.7.

**Comment by maphilli14** [comment]
I assume you mean by copying the code and pasting into a custom card?  It doesn't seem to work, how are the LAT and LONG passed?

![image](https://user-images.githubusercontent.com/6034105/186181488-6af5fd64-fcdd-42fa-9fbe-4bca8a80d305.png)

**Comment by mawinkler** [comment]
When you install the AstroWeather integration you'll get a weather entity. It does start with `weather.astroweather_` followed by your configured longitude and latitude (`.` is replaced with `_`).
Example: `weather.astroweather_46_123_12_987` for LONGITUTE: 46.123 and LATITUDE: 12.987
Look for it either in the Developer Tools -> States or Settings -> Devices & Services -> AstroWeather -> Entities.

**Comment by maphilli14** [comment]
I touched the files again ; updated lovelace resources etc...


![image](https://user-images.githubusercontent.com/6034105/186248282-e2fb678b-a307-436f-9440-de92137c7c6d.png)


still adding the custom card I get:


![image](https://user-images.githubusercontent.com/6034105/186248539-914d00e4-340a-4ee8-8c7d-9c0d20616c56.png)
![image](https://user-images.githubusercontent.com/6034105/186248730-212cbc6b-a8a3-4fa9-8b79-7a5b1365c663.png)
![image](https://user-images.githubusercontent.com/6034105/186248747-c2386b23-b18f-46e6-a521-1c9ad0dbb86f.png)

**Comment by mawinkler** [comment]
Have you checked the logfile of home assistant?
Which version of the AstroWeather integration are you using?
Did you install via HACS?

You could also enable debug logging for AstroWeather by adding the following in your configuration.yaml:
```yaml
logger:
  default: warning
  logs:
    custom_components.astroweather: debug
    pyastroweatherio: debug
```

**Comment by maphilli14** [comment]
I didn't turn on logging yet but did find this:

```
Logger: homeassistant.components.weather
Source: components/weather/__init__.py:132
Integration: Weather ([documentation](https://www.home-assistant.io/integrations/weather), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+weather%22))
First occurred: August 23, 2022 at 2:12:55 PM (4 occurrences)
Last logged: August 23, 2022 at 3:19:24 PM

    Error adding entities for domain weather with platform astroweather
    Error while setting up astroweather platform for weather

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 810, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 533, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 573, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 210, in state_attributes
    if self.temperature is not None:
  File "/usr/src/homeassistant/homeassistant/components/weather/__init__.py", line 132, in temperature
    return self._attr_temperature
AttributeError: 'AstroWeatherWeather' object has no attribute '_attr_temperature'
```
