### ISSUE TITLE
Inconsistent formatting on wider cards

### ISSUE THREAD

**Issue by CMDR-Sloma** [mawinkler/astroweather-card#6]
Hi, this is great card, thanks for creating it but...

I have widescreen monitor and on my dashboard I use wider cards with width of 400. This creates a slight issue for this card, specifically for the forecast element. 

When dashboard's card is this wide, I have to increase forecast day count to at least 9 in order to display vertical icons that corresponds to forecast's elements. This probably has something to do with the formatting of the forecast? I suspect icons are placed in a horizontal line within the table's column? When you increase the number of days, it "squeezes" the column and thus forces all icons to align vertically, am I right? 

I know picture says a thousand words and would better illustrate the issue, so here it is:
![image](https://user-images.githubusercontent.com/46288478/184471822-c8a1bfce-cb7e-442a-8bc0-7f7671c59839.png)

And my weather view config:
![image](https://user-images.githubusercontent.com/46288478/184471777-6db908b0-67f6-4258-baab-ecae245abe44.png)

I hope this helps,

Thanks.

**Comment by mawinkler** [comment]
Thank you for reporting. The issue is fixed in release v0.22.2.
