### ISSUE TITLE
Custom element doesn't exist: astroweather-card

### ISSUE THREAD

**Issue by travisengh** [mawinkler/astroweather-card#7]
I followed all of the instructions and am consistantly getting this error no matter what I do:

Custom element doesn't exist: astroweather-card

**Comment by ne-vial** [comment]
For me, it doesn't. Weird thing is that on the companion Android app, everything works fine. But if I use the same dashboard, I get the error message. Tried to reinstall astroweather-card, to change the lovelace resource, to delete browser cache, but nothing works

**Comment by mawinkler** [comment]
The lovelace card requires the custom astroweather weather entity, so @Jamiro75 you're right. The card does also test for this displays an error if a wrong weather entity is used.
@ne-vial : have you tried clearing your cache?

**Comment by ne-vial** [comment]
> @ne-vial : have you tried clearing your cache?
Yes, I already tried that

**Comment by mawinkler** [comment]
should be solved now with v0.23.0

**Comment by lead0r** [comment]
> should be solved now with v0.23.0

for me, it's not. I am on 0.23.1 and cleared all browser cacher before trying

**Comment by DuckersMcQuack** [comment]
Same error here. Don't know what lovelace is, nor do i know if i need it. 

Placed the .js files in /config/www/custom-lovelace/astroweather-card/astroweather-card.js
Assuming it was supposed to be .js and not .ts as they appear in src folder? Cause the clicky links on the main page redirects to a 404.

**Comment by mawinkler** [comment]
Hi,

The .ts files are the sources only, you need to use the .js file from the latest release:

https://github.com/mawinkler/astroweather-card/releases/tag/v0.74.2￼
Thank you for pointing me to a documentation error :-) Will fix it shortly

Cheers,
Markus
